// generated by csbindgen — do not edit
// regenerate with: cargo build -p lunar-ffi
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Lunar.Native;

internal static unsafe partial class LunarNative
{
    [LibraryImport("lunar_ffi")]
    internal static partial uint LunarSpawn(LunarWorld* world);

    [LibraryImport("lunar_ffi")]
    internal static partial void LunarDespawn(LunarWorld* world, uint entity);

    [LibraryImport("lunar_ffi")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarAlive(LunarWorld* world, uint entity);

    [LibraryImport("lunar_ffi")]
    internal static partial uint LunarComponentRegister(
        LunarWorld* world, byte* name, nuint size, nuint alignment);

    [LibraryImport("lunar_ffi")]
    internal static partial uint LunarComponentId(LunarWorld* world, byte* name);

    [LibraryImport("lunar_ffi")]
    internal static partial void LunarComponentInsert(
        LunarWorld* world, uint entity, uint componentId, void* data, nuint size);

    [LibraryImport("lunar_ffi")]
    internal static partial void LunarComponentRemove(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarComponentHas(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi")]
    internal static partial void* LunarComponentGet(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi")]
    internal static partial void* LunarComponentGetMut(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarGetTransform3d(
        LunarWorld* world, uint entity, LunarTransform3d* outValue);

    [LibraryImport("lunar_ffi")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarSetTransform3d(
        LunarWorld* world, uint entity, LunarTransform3d* value);

    [LibraryImport("lunar_ffi")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarGetTransform2d(
        LunarWorld* world, uint entity, LunarTransform2d* outValue);

    [LibraryImport("lunar_ffi")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarSetTransform2d(
        LunarWorld* world, uint entity, LunarTransform2d* value);

    [LibraryImport("lunar_ffi")]
    internal static partial void LunarQueryForeach(
        LunarWorld* world,
        uint* include, nuint includeCount,
        uint* exclude, nuint excludeCount,
        delegate* unmanaged[Cdecl]<uint, void*, void> callback,
        void* userData);

    [LibraryImport("lunar_ffi")]
    internal static partial uint LunarSystemRegister(
        LunarWorld* world, uint schedule,
        delegate* unmanaged[Cdecl]<LunarWorld*, void*, void> callback,
        void* userData);

    [LibraryImport("lunar_ffi")]
    internal static partial void LunarSystemUnregister(LunarWorld* world, uint systemId);

    [LibraryImport("lunar_ffi")]
    internal static partial float LunarDeltaSeconds(LunarWorld* world);

    [LibraryImport("lunar_ffi")]
    internal static partial float LunarElapsedSeconds(LunarWorld* world);
}

/// <summary>opaque engine world — only valid during a system callback.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct LunarWorld { }

/// <summary>portable 3D transform: 40 bytes, 4-byte aligned.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct LunarTransform3d
{
    public LunarVec3 Translation;
    public LunarQuat Rotation;
    public LunarVec3 Scale;
}

/// <summary>portable 2D transform: 20 bytes, 4-byte aligned.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct LunarTransform2d
{
    public LunarVec2 Translation;
    public float     Rotation;
    public LunarVec2 Scale;
}

[StructLayout(LayoutKind.Sequential)]
internal struct LunarVec2 { public float X; public float Y; }

[StructLayout(LayoutKind.Sequential)]
internal struct LunarVec3 { public float X; public float Y; public float Z; }

[StructLayout(LayoutKind.Sequential)]
internal struct LunarQuat { public float X; public float Y; public float Z; public float W; }
