// generated by csbindgen: do not edit
// regenerate with: cargo build -p lunar-ffi
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Lunar.Native;

internal static unsafe partial class LunarNative
{
    [LibraryImport("lunar_ffi", EntryPoint = "lunar_spawn")]
    internal static partial uint LunarSpawn(LunarWorld* world);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_despawn")]
    internal static partial void LunarDespawn(LunarWorld* world, uint entity);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_alive")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarAlive(LunarWorld* world, uint entity);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_component_register")]
    internal static partial uint LunarComponentRegister(
        LunarWorld* world, byte* name, nuint size, nuint alignment);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_component_id")]
    internal static partial uint LunarComponentId(LunarWorld* world, byte* name);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_component_insert")]
    internal static partial void LunarComponentInsert(
        LunarWorld* world, uint entity, uint componentId, void* data, nuint size);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_component_remove")]
    internal static partial void LunarComponentRemove(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_component_has")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarComponentHas(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_component_get")]
    internal static partial void* LunarComponentGet(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_component_get_mut")]
    internal static partial void* LunarComponentGetMut(
        LunarWorld* world, uint entity, uint componentId);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_get_transform3d")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarGetTransform3d(
        LunarWorld* world, uint entity, LunarTransform3d* outValue);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_set_transform3d")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarSetTransform3d(
        LunarWorld* world, uint entity, LunarTransform3d* value);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_get_transform2d")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarGetTransform2d(
        LunarWorld* world, uint entity, LunarTransform2d* outValue);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_set_transform2d")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarSetTransform2d(
        LunarWorld* world, uint entity, LunarTransform2d* value);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_query_foreach")]
    internal static partial void LunarQueryForeach(
        LunarWorld* world,
        uint* include, nuint includeCount,
        uint* exclude, nuint excludeCount,
        delegate* unmanaged[Cdecl]<uint, void*, void> callback,
        void* userData);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_system_register")]
    internal static partial uint LunarSystemRegister(
        LunarWorld* world, uint schedule,
        delegate* unmanaged[Cdecl]<LunarWorld*, void*, void> callback,
        void* userData);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_system_unregister")]
    internal static partial void LunarSystemUnregister(LunarWorld* world, uint systemId);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_delta_seconds")]
    internal static partial float LunarDeltaSeconds(LunarWorld* world);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_elapsed_seconds")]
    internal static partial float LunarElapsedSeconds(LunarWorld* world);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_input_key_held")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarInputKeyHeld(LunarWorld* world, uint key);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_input_key_just_pressed")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarInputKeyJustPressed(LunarWorld* world, uint key);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_input_mouse_delta")]
    internal static partial void LunarInputMouseDelta(LunarWorld* world, float* outDx, float* outDy);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_input_gamepad_axis")]
    internal static partial float LunarInputGamepadAxis(LunarWorld* world, uint gamepadIndex, uint axis);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_get_main_camera")]
    internal static partial uint LunarGetMainCamera(LunarWorld* world);

    // ── scene setup ──────────────────────────────────────────────────────────

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_set_cursor_locked")]
    internal static partial void LunarSetCursorLocked(LunarWorld* world,
        [MarshalAs(UnmanagedType.U1)] bool locked);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_set_sky")]
    internal static partial void LunarSetSky(LunarWorld* world,
        float skyR, float skyG, float skyB,
        float sunR, float sunG, float sunB,
        [MarshalAs(UnmanagedType.U1)] bool showSun);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_set_quality")]
    internal static partial void LunarSetQuality(LunarWorld* world,
        uint msaaSamples,
        [MarshalAs(UnmanagedType.U1)] bool staa,
        float renderScale,
        [MarshalAs(UnmanagedType.U1)] bool bloom,
        [MarshalAs(UnmanagedType.U1)] bool ssao,
        uint shadowRes,
        uint shadowCascades);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_mesh_quad")]
    internal static partial ulong LunarMeshQuad(LunarWorld* world, float halfX, float halfZ);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_mesh_box")]
    internal static partial ulong LunarMeshBox(LunarWorld* world, float hx, float hy, float hz);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_mesh_sphere")]
    internal static partial ulong LunarMeshSphere(LunarWorld* world,
        float radius, uint sectors, uint stacks);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_mesh_cylinder")]
    internal static partial ulong LunarMeshCylinder(LunarWorld* world,
        float radius, float height, uint sectors,
        [MarshalAs(UnmanagedType.U1)] bool caps);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_material_create")]
    internal static partial ulong LunarMaterialCreate(LunarWorld* world,
        float r, float g, float b, float a, uint shading);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_spawn_mesh")]
    internal static partial uint LunarSpawnMesh(LunarWorld* world,
        ulong meshHandle, ulong matHandle, float x, float y, float z);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_spawn_camera")]
    internal static partial uint LunarSpawnCamera(LunarWorld* world,
        float x, float y, float z, float fovY, float near, float far);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_set_active_camera")]
    internal static partial void LunarSetActiveCamera(LunarWorld* world, uint entity);

    // ── hot reload ───────────────────────────────────────────────────────────

    /// <summary>true when <c>lunar_plugin_init</c> is being called during a hot reload.</summary>
    [LibraryImport("lunar_ffi", EntryPoint = "lunar_is_reload")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarIsReload(LunarWorld* world);

    // ── per-entity behaviors ───────────────────────────────────────────────────

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_register")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarBehaviorRegister(
        LunarWorld* world, byte* id,
        delegate* unmanaged[Cdecl]<byte*, ulong> factory,
        delegate* unmanaged[Cdecl]<ulong, LunarWorld*, uint, uint, void> lifecycle,
        delegate* unmanaged[Cdecl]<ulong, uint> fieldCount,
        delegate* unmanaged[Cdecl]<ulong, uint, LunarFieldSchema*, byte> fieldSchema,
        delegate* unmanaged[Cdecl]<ulong, byte*, LunarFieldValue*, byte> getField,
        delegate* unmanaged[Cdecl]<ulong, byte*, LunarFieldValue*, byte> setField,
        delegate* unmanaged[Cdecl]<ulong, void> dropInstance);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_attach")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarBehaviorAttach(LunarWorld* world, uint entity, byte* id);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_detach")]
    internal static partial uint LunarBehaviorDetach(LunarWorld* world, uint entity, byte* id);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_count")]
    internal static partial uint LunarBehaviorCount(LunarWorld* world, uint entity);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_field_count")]
    internal static partial uint LunarBehaviorFieldCount(
        LunarWorld* world, uint entity, uint behaviorIndex);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_field_schema")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarBehaviorFieldSchema(
        LunarWorld* world, uint entity, uint behaviorIndex, uint fieldIndex,
        LunarFieldSchema* outSchema);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_get_field")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarBehaviorGetField(
        LunarWorld* world, uint entity, uint behaviorIndex, byte* name,
        LunarFieldValue* outValue);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_behavior_set_field")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarBehaviorSetField(
        LunarWorld* world, uint entity, uint behaviorIndex, byte* name,
        LunarFieldValue* value);

    // ── behavior event channels ────────────────────────────────────────────────

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_event_emit")]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static partial bool LunarEventEmit(
        LunarWorld* world, byte* channel, byte* payload, nuint len);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_event_count")]
    internal static partial uint LunarEventCount(LunarWorld* world, byte* channel);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_event_get")]
    internal static partial nint LunarEventGet(
        LunarWorld* world, byte* channel, uint index, byte* outBuffer, nuint capacity);

    [LibraryImport("lunar_ffi", EntryPoint = "lunar_event_clear")]
    internal static partial void LunarEventClear(LunarWorld* world, byte* channel);
}

/// <summary>tagged-union behavior field value, matching the FFI LunarFieldValue.</summary>
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct LunarFieldValue
{
    public uint Kind;
    public float FloatValue;
    public long IntValue;
    public byte BoolValue;
    public fixed float Vec[4];
    public byte* Text;
}

/// <summary>exported-field schema entry, matching the FFI LunarFieldSchema.</summary>
[StructLayout(LayoutKind.Sequential)]
internal unsafe struct LunarFieldSchema
{
    public fixed byte Name[64];
    public uint Kind;
}

/// <summary>
/// opaque engine world handle. only valid during a system callback.
/// don't construct or dereference this type: pass it straight to <see cref="World"/>.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct LunarWorld { }

/// <summary>portable 3D transform: 40 bytes, 4-byte aligned.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct LunarTransform3d
{
    public LunarVec3 Translation;
    public LunarQuat Rotation;
    public LunarVec3 Scale;
}

/// <summary>portable 2D transform: 20 bytes, 4-byte aligned.</summary>
[StructLayout(LayoutKind.Sequential)]
internal struct LunarTransform2d
{
    public LunarVec2 Translation;
    public float     Rotation;
    public LunarVec2 Scale;
}

[StructLayout(LayoutKind.Sequential)]
internal struct LunarVec2 { public float X; public float Y; }

[StructLayout(LayoutKind.Sequential)]
internal struct LunarVec3 { public float X; public float Y; public float Z; }

[StructLayout(LayoutKind.Sequential)]
internal struct LunarQuat { public float X; public float Y; public float Z; public float W; }
