using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

/// <summary>
/// generates the <c>[UnmanagedCallersOnly]</c> entry point for any class tagged
/// <c>[LunarPlugin]</c>. exactly one such class per assembly is expected.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class LunarPluginGenerator : IIncrementalGenerator
{
    const string AttributeFqn = "Lunar.LunarPluginAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var plugins = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
            .Where(static symbol => symbol is not null)
            .Collect();

        context.RegisterSourceOutput(plugins, Emit);
    }

    static void Emit(SourceProductionContext ctx, ImmutableArray<INamedTypeSymbol?> symbols)
    {
        if (symbols.IsDefaultOrEmpty) return;

        // report diagnostic for duplicates
        for (int i = 1; i < symbols.Length; i++)
        {
            if (symbols[i] is not { } extra) continue;
            ctx.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "LUNAR001",
                    title: "multiple [LunarPlugin] classes",
                    messageFormat: "only one [LunarPlugin] class per assembly is allowed; '{0}' is ignored",
                    category: "LunarPlugin",
                    defaultSeverity: DiagnosticSeverity.Warning,
                    isEnabledByDefault: true),
                location: null,
                extra.ToDisplayString()));
        }

        if (symbols[0] is not { } symbol) return;

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();
        var qualifiedName = ns.Length > 0 ? $"{ns}.{symbol.Name}" : symbol.Name;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine("using System.Runtime.InteropServices;");
        source.AppendLine("using Lunar;");
        source.AppendLine();
        source.AppendLine($"// entry point generated from [LunarPlugin] on {qualifiedName}");
        source.AppendLine("file static class LunarGeneratedEntryPoint");
        source.AppendLine("{");
        source.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"lunar_plugin_init\", CallConvs = [typeof(CallConvCdecl)])]");
        source.AppendLine($"    public static unsafe void Init(void* world) => Plugin.Run(world, new {qualifiedName}());");
        source.AppendLine("}");

        ctx.AddSource("LunarPlugin.g.cs", source.ToString());
    }
}
