#ifndef LUNAR_H
#define LUNAR_H

/* generated by cbindgen — do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define LUNAR_SCHEDULE_STARTUP 0

#define LUNAR_SCHEDULE_UPDATE 1

#define LUNAR_SCHEDULE_FIXED_UPDATE 2

#define LUNAR_SCHEDULE_SHUTDOWN 3

// opaque handle to the engine world — only valid during a system callback.
//
// the engine passes a pointer to its internal [`bevy_ecs::world::World`].
// never construct or dereference this type directly.
typedef struct LunarWorld LunarWorld;

// component type identifier — stable for the lifetime of the world.
typedef uint32_t LunarComponentId;

// registered system identifier — used to unregister systems.
typedef uint32_t LunarSystemId;

// entity identifier — index into the world's entity table.
typedef uint32_t LunarEntity;

typedef struct LunarVec2 {
    float x;
    float y;
} LunarVec2;

typedef struct LunarVec3 {
    float x;
    float y;
    float z;
} LunarVec3;

// quaternion in portable C layout (4-byte aligned, 16 bytes).
//
// the engine's internal `glam::Quat` may have 16-byte alignment on SIMD builds.
// the typed accessors (`lunar_get_transform3d` etc.) handle the conversion —
// do not use raw component access for `LocalTransform3d`.
typedef struct LunarQuat {
    float x;
    float y;
    float z;
    float w;
} LunarQuat;

// 3D transform in portable C layout: 40 bytes, 4-byte aligned.
typedef struct LunarTransform3d {
    struct LunarVec3 translation;
    struct LunarQuat rotation;
    struct LunarVec3 scale;
} LunarTransform3d;

// 2D transform in portable C layout: 20 bytes, 4-byte aligned.
// matches the engine's [`LocalTransform`] layout exactly.
typedef struct LunarTransform2d {
    struct LunarVec2 translation;
    float rotation;
    struct LunarVec2 scale;
} LunarTransform2d;

typedef void (*LunarQueryFn)(LunarEntity, void*);

typedef void (*LunarSystemFn)(struct LunarWorld*, void*);

#define LUNAR_INVALID_COMPONENT_ID UINT32_MAX

#define LUNAR_INVALID_SYSTEM_ID UINT32_MAX

#endif  /* LUNAR_H */
